trigger:
- main

strategy:
  matrix:
    linux:
      os: 'ubuntu-latest'
    mac:
      os: 'macos-latest'

pool:
  vmImage: $(os)

steps:
- script: echo Running on $(os)
  displayName: 'Run a one-line script'
